/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryproj;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Amin
 */
public class BookAuthorsWindow extends javax.swing.JDialog {
    
    public static int book_id_length = 10;
    public static int author_length = 80;
    public static int title_length = 80;
    public static int addr_length = 80;
    public static int phone_length = 14;
    public static int branch_length = 30;
    public static int card_no_length = 10;
    public static int Type_length = 1;
    
    
        public static String checkApostrophe(String inputString) {
        String str;
        String begin;
        String end;

        str = inputString;
        for (int i = 0; i < inputString.length(); i++) {
            if (inputString.charAt(i) == '\'') {
                begin = inputString.substring(0, i);
                end = inputString.substring(i + 1);
                str = begin + "''" + end;
                break;
            }
        }

        return str;
    }

    /**
     * Creates new form BookAuthorsWindow
     */
    public BookAuthorsWindow(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpenFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        OpenFile.setText("Open File");
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
        JFileChooser fileopen = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("Text/CSV file", "txt", "csv");
        fileopen.addChoosableFileFilter(filter);
        fileopen.showOpenDialog(this);
        File file = fileopen.getSelectedFile();
        
        int count = 0;
        try {
            
            Connection conn = null;

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", "ENmPqspN");
            Statement stmt = conn.createStatement();

            stmt.execute("CREATE DATABASE IF NOT EXISTS Library ;");
            stmt.execute("use Library;");

            //table already exists --> drop it and then create
            ResultSet rs = stmt.executeQuery("SHOW TABLES LIKE 'BOOK_AUTHORS';");
            if (rs.next()) {
                stmt.execute("DROP TABLE BOOK_AUTHORS");
            }
            rs = stmt.executeQuery("SHOW TABLES LIKE 'BOOK';");
            if (rs.next()) {
                stmt.execute("DROP TABLE BOOK");
            }

            try (
                    BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                String split_line[];
                String split_authors[];
                String split_authorName[];
                String book_id;
                String author_name;
                String title;
                
                
                line = reader.readLine();// Dismiss header line
                //split_line = line.split("\t");
                
                stmt.execute("CREATE TABLE BOOK ( "
                        + "book_id varchar(" + book_id_length + ") NOT NULL PRIMARY KEY,"
                        + "title varchar(" + title_length + ") NOT NULL); ");
                
                stmt.execute("CREATE TABLE BOOK_AUTHORS ( "
                        + "book_id varchar(" + book_id_length + ") NOT NULL,"
                        + "author_name varchar(" + author_length + ") NOT NULL,"
                        //+ "fname" + " varchar(" + fname_length + "), "
                        //+ "minit" + " varchar(" + mname_length + ") default NULL, "
                        //+ "Type int(" + Type_length + ") NOT NULL,"
                        + "Type int NOT NULL,"
                        + "PRIMARY KEY (book_id, author_name)) ");



                while ((line = reader.readLine()) != null) //start to read books_authors table
                {
                    line = checkApostrophe(line);
                    split_line = line.split("\t");
                    book_id = split_line[0];
                    author_name = split_line[1];
                    title = split_line[2];
                    
                    int counter = 0;
                    for( int i=0; i<author_name.length(); i++)
                    {
                        if( author_name.charAt(i) == ',' )
                        counter++;
                    }
                    
                    //Split authors from each other
                    //String fname = "", mname = "NULL", lname = "";
                    
                    
                    int Type = 0;
                    String parts[] = null;
                    
                    if( counter == 0 )
                    {

                        split_authorName = author_name.split(" ");
                        if( (split_authorName.length >= 5) )
                            Type = 1;
                        
                        if( split_authorName[0].equals("Various") || split_authorName[0].equals("The"))
                            Type = 1;

                        
                        /*  is it necessary to remove other info about author like (Editor) ?
                        if( author_name.contains("(") )
                        {
                            
                            parts = author_name.split( "\\(" ) ;
                            author_name = parts[0];
                        }
                        */
                        
                        stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                                            + book_id + "','"
                                            + author_name + "','"
                                            + Type
                                            + "');");
                        stmt.execute("INSERT INTO BOOK VALUES ('"
                                            + book_id + "','"
                                            + title + "');");

                        
                        /* split Fname, Minit, Lname
                        split_authorName = author_name.split(" ");
                        
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            if(split_authorName[1].charAt(1) == '.')
                            {
                                mname = split_authorName[1].charAt(0) + "" ;
                            } else
                                mname = split_authorName[1];
                            
                            lname = split_authorName[2];
                        }else if ( (split_authorName.length >= 5) || (split_authorName.length == 1) )
                        {
                            fname = "NULL";
                            lname = "NULL";
                        }
                        else if ( split_authorName.length == 4 )
                        {
                            fname = split_authorName[0]  ;
                            mname = split_authorName[1] + " " + split_authorName[2];
                            lname = split_authorName[3];
                        }
                        */
                        
                        
                /* is it necessary to remove other info about author like (Editor) ?
                if ( parts != null )
                {
                            stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + parts[0] + "(" + parts[1] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    stmt.execute("INSERT INTO BOOK VALUES ('"
                            + book_id + "','"
                            + title + "');");
                    
                }
                else
                {
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + author_name + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    stmt.execute("INSERT INTO BOOK VALUES ('"
                            + book_id + "','"
                            + title + "');");
                }
                */
                        
    } //end if(counter == 0)
                    
                    
                    
                    
                   /* 
                    fname = ""; 
                    mname = "NULL"; 
                    lname = "";
                    */
                    
                    
                    
                    if( counter == 1 )
                    {
                        split_authors = author_name.split(", ");
                        
                        stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                                            + book_id + "','"
                                            + split_authors[0] + "','"
                                            + Type
                                            + "');");
                        stmt.execute("INSERT INTO BOOK VALUES ('"
                                            + book_id + "','"
                                            + title + "');");
                        
                        
                        stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                                            + book_id + "','"
                                            + split_authors[1] + "','"
                                            + Type
                                            + "');");

                        
                        /*  is it necessary to remove other info about author like (Editor) ?
                        if( split_authors[0].contains("(") )
                        {
                            
                            parts = split_authors[0].split( "\\(" ) ;
                            split_authors[0] = parts[0];
                        }
                        */
                        
                        
                        
                        /*
                        split_authorName = split_authors[0].split(" ");
                        
                        if(split_authorName.length == 1)
                        {
                            lname = split_authors[0];
                            fname = split_authors[1];
                            
                            
                            stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + fname + " " + lname + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    stmt.execute("INSERT INTO BOOK VALUES ('"
                            + book_id + "','"
                            + title + "');");
                        }
                        else if(split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                            
                if ( parts != null )
                {
                            stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + parts[0] + "(" + parts[1] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    stmt.execute("INSERT INTO BOOK VALUES ('"
                            + book_id + "','"
                            + title + "');");
                    
                }
                else
                {
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[0] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    stmt.execute("INSERT INTO BOOK VALUES ('"
                            + book_id + "','"
                            + title + "');");
                }
                            

                    
                    

                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                                stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[0] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    stmt.execute("INSERT INTO BOOK VALUES ('"
                            + book_id + "','"
                            + title + "');");

                        }
                        
                        */
                        
                        /*
                        //  is it necessary to remove other info about author like (Editor) ?
                        if( split_authors[1].contains("(") )
                        {
                            
                            parts = split_authors[1].split( "\\(" ) ;
                            split_authors[1] = parts[0];
                        }
                        split_authorName = split_authors[1].split(" ");
                        
                        
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                            
                if ( parts != null )
                {
                            stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + parts[0] + "(" + parts[1] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");

                    
                }
                else
                {
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[1] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");

                }
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                            
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[1] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");

                        }
                        */
  
                    }//end of if( counter == 1)
                    
                    if( counter == 2 )
                    {
                        split_authors = author_name.split(", ");

                        
                        stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                                            + book_id + "','"
                                            + split_authors[0] + "','"
                                            + Type
                                            + "');");
                        stmt.execute("INSERT INTO BOOK VALUES ('"
                                            + book_id + "','"
                                            + title + "');");
                        
                        
                        stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                                            + book_id + "','"
                                            + split_authors[1] + "','"
                                            + Type
                                            + "');");
                        
                        stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                                            + book_id + "','"
                                            + split_authors[2] + "','"
                                            + Type
                                            + "');");
                        
                        /*
                        split_authorName = split_authors[0].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[0] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    stmt.execute("INSERT INTO BOOK VALUES ('"
                            + book_id + "','"
                            + title + "');");
                    
                    fname = ""; 
                    mname = "NULL"; 
                    lname = "";
                    
                        split_authorName = split_authors[1].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[1] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");

                    
                    fname = ""; 
                    mname = "NULL"; 
                    lname = "";
                    
                    split_authorName = split_authors[2].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[2] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");

                        */
                        
                    } //end of if( counter == 2 )
                    
                    
                    if( counter == 3 )
                    {
                        split_authors = author_name.split(", ");
                        
                        stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                                            + book_id + "','"
                                            + split_authors[0] + "','"
                                            + Type
                                            + "');");
                        stmt.execute("INSERT INTO BOOK VALUES ('"
                                            + book_id + "','"
                                            + title + "');");
                        
                        
                        stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                                            + book_id + "','"
                                            + split_authors[1] + "','"
                                            + Type
                                            + "');");
                        
                        stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                                            + book_id + "','"
                                            + split_authors[2] + "','"
                                            + Type
                                            + "');");
                        
                        stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                                            + book_id + "','"
                                            + split_authors[3] + "','"
                                            + Type
                                            + "');");
                        
                        /*
                        split_authorName = split_authors[0].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[0] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    stmt.execute("INSERT INTO BOOK VALUES ('"
                            + book_id + "','"
                            + title + "');");
                    
                    fname = ""; 
                    mname = "NULL"; 
                    lname = "";
                    
                        split_authorName = split_authors[1].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[1] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");

                    
                    fname = ""; 
                    mname = "NULL"; 
                    lname = "";
                    
                    split_authorName = split_authors[2].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[2] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    
                    
                        split_authorName = split_authors[3].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[3] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");

                        
                    }
                    
                    
                    if( counter == 4 )
                    {
                        split_authors = author_name.split(", ");
                        
                        
                        split_authorName = split_authors[0].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[0] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    stmt.execute("INSERT INTO BOOK VALUES ('"
                            + book_id + "','"
                            + title + "');");
                    
                    fname = ""; 
                    mname = "NULL"; 
                    lname = "";
                    
                        split_authorName = split_authors[1].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[1] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");

                    
                    fname = ""; 
                    mname = "NULL"; 
                    lname = "";
                    
                    split_authorName = split_authors[2].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[2] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    
                    
                    fname = ""; 
                    mname = "NULL"; 
                    lname = "";
                        split_authorName = split_authors[3].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[3] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                    
                    
                    fname = ""; 
                    mname = "NULL"; 
                    lname = "";
                        split_authorName = split_authors[4].split(" ");
                        if (split_authorName.length == 2)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            lname = split_authorName[1];
                        }else if (split_authorName.length == 3)
                        {
                            if(split_authorName[0].charAt(1) == '.')
                            {
                                fname = split_authorName[0].charAt(0) + "" ;
                            } else
                                fname = split_authorName[0];
                            
                            mname = split_authorName[1].charAt(0) + "";
                            lname = split_authorName[2];
                        }
                        
                    stmt.execute("INSERT INTO BOOK_AUTHORS VALUES ('"
                            + book_id + "','"
                            + split_authors[4] + "','"
                            + fname + "','"
                            + mname + "','"
                            + lname
                            + "');");
                        
                        */

                        
                    }// end of if( counter == 3 )
                    
                    
                    
            }//end of reading data file
            }
            conn.close();
            System.out.println("Book Authors Data loaded");
            this.dispose();
        } catch (SQLException ex) {
            System.out.println("Error in connection: " + ex.getMessage());
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
			ex.printStackTrace();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
			ex.printStackTrace();
        }
       
        
            
    }//GEN-LAST:event_OpenFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookAuthorsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookAuthorsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookAuthorsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookAuthorsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BookAuthorsWindow dialog = new BookAuthorsWindow(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OpenFile;
    // End of variables declaration//GEN-END:variables
}
