/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryproj;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Amin
 */
public class BorrowersWindow extends javax.swing.JDialog {
    
    public static int book_id_length = 10;
    public static int author_length = 80;
    public static int title_length = 80;
    public static int fname_length = 30;
    public static int mname_length = 1;
    public static int lname_length = 30;
    public static int addr_length = 80;
    public static int phone_length = 14;
    public static int branch_length = 30;
    public static int card_no_length = 10;
    
        public static String checkApostrophe(String inputString) {
        String str;
        String begin;
        String end;

        str = inputString;
        for (int i = 0; i < inputString.length(); i++) {
            if (inputString.charAt(i) == '\'') {
                begin = inputString.substring(0, i);
                end = inputString.substring(i + 1);
                str = begin + "''" + end;
                break;
            }
        }

        return str;
    }

    /**
     * Creates new form BorrowersWindow
     */
    public BorrowersWindow(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpenFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        OpenFile.setText("Open File");
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(OpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
        JFileChooser fileopen = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("Text/CSV file", "txt", "csv");
        fileopen.addChoosableFileFilter(filter);
        fileopen.showOpenDialog(this);
        File file = fileopen.getSelectedFile();
        
        
        int count = 0;
        try {
            
            Connection conn = null;

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/", "root", "ENmPqspN");
            Statement stmt = conn.createStatement();

            stmt.execute("CREATE DATABASE IF NOT EXISTS Library ;");

            stmt.execute("use Library;");

            //table already exists --> drop it and then create
            ResultSet rs = stmt.executeQuery("SHOW TABLES LIKE 'BORROWER';");
            if (rs.next()) {
                stmt.execute("DROP TABLE BORROWER");
            }

            try ( //READ from file
                    BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                String split_line[];
                String split_author[];
                int card_no;
                String fname;
                String lname;
                String address;
                String addr, city, state;
                String phone;

                line = reader.readLine();// Dismiss heading line
                split_line = line.split("\t");
                stmt.execute("CREATE TABLE BORROWER ( "
                        + "card_no int NOT NULL PRIMARY KEY, "
                        + "fname varchar(" + fname_length + "),"
                        + "lname varchar(" + lname_length + "),"
                        + "address varchar(" + addr_length + "),"
                        + "phone varchar(" + phone_length + ")) ");

                while ((line = reader.readLine()) != null) {
                    line = checkApostrophe(line);
                    split_line = line.split("\t");
                    card_no = Integer.parseInt(split_line[0]);
                    fname = split_line[1];
                    lname = split_line[2];
                    addr = split_line[3];
                    city = split_line[4];
                    state = split_line[5];
                    address = addr + ", " + city + ", " + state;
                    phone = split_line[6];

                    stmt.execute("INSERT INTO BORROWER VALUES ('"
                            + card_no + "','"
                            + fname + "','"
                            + lname + "','"
                            + address + "','"
                            + phone + "');");
                }
            }
            conn.close();
            System.out.println("Borrowers Data loaded");
            this.dispose();
        } catch (SQLException ex) {
            System.out.println("Error in connection: " + ex.getMessage());
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
			ex.printStackTrace();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
			ex.printStackTrace();
        }
    }//GEN-LAST:event_OpenFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowersWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowersWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowersWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowersWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BorrowersWindow dialog = new BorrowersWindow(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OpenFile;
    // End of variables declaration//GEN-END:variables
}
