package libraryproj;

/**
 *
 * @author Amin
 */

import javax.swing.table.DefaultTableModel;


public class Checkinwindow extends javax.swing.JDialog {


    public Checkinwindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CheckinBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        CheckinTable = new javax.swing.JTable();
        CheckinButton = new javax.swing.JButton();
        CancelButtton = new javax.swing.JButton();
        CheckinText = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Check in by:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 30));

        CheckinBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Book id", "Card number", "Borrower name" }));
        CheckinBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckinBoxActionPerformed(evt);
            }
        });
        jPanel1.add(CheckinBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 130, 30));

        CheckinTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Loan id", "Book id", "Branch id", "Card no", "Date out", "Due date", "Date in"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CheckinTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 720, 240));

        CheckinButton.setText("CHECK IN");
        CheckinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckinButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CheckinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 150, 60));

        CancelButtton.setText("CANCEL");
        CancelButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButttonActionPerformed(evt);
            }
        });
        jPanel1.add(CancelButtton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 150, 60));
        jPanel1.add(CheckinText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 280, 30));

        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryproj/icon/6869024_xmag.png"))); // NOI18N
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 60, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButttonActionPerformed

    private void CheckinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckinButtonActionPerformed
        int row = CheckinTable.getSelectedRow();
        Main.checkin(row, tablemodel, CheckinTable);
    }//GEN-LAST:event_CheckinButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
       tablemodel = Main.checkindisplay(CheckinTable, CheckinBox.getSelectedItem().toString(),CheckinText.getText().toString());
       
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void CheckinBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckinBoxActionPerformed

    }//GEN-LAST:event_CheckinBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkinwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkinwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkinwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkinwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Checkinwindow dialog = new Checkinwindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private DefaultTableModel tablemodel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButtton;
    private javax.swing.JComboBox CheckinBox;
    private javax.swing.JButton CheckinButton;
    private javax.swing.JTable CheckinTable;
    private javax.swing.JTextField CheckinText;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
